baseURL = 'http://poganatz.ca/'
languageCode = 'en-us'
title = "Alexander Poganatz's Website"
theme = "hugo-coder"
defaultContentLangauge = "en-us"

paginate = 20

[markup.highlight]
style = 'github-dark'

[params]
	author = "Alexander Poganatz"
	info = "Software Developer"
	keywords = 'blog,developer,personal'
	avatarurl = "images/avatar.jpg"

	# a bunch of favicons
	since = 2017
	colorScheme = "auto"
	hideColorSchemeToggle = "false"

[[menu.main]]
	name = "Blog"
	weight = 1
	url = "posts/"

[[menu.main]]
	name = "About"
	weight = 2
	url = "about"

[[params.social]]
	name = "Github"
	icon = "fa fa-github fa-2x"
	weight = 1
	url = "https://github.com/Alexander-Poganatz"

[[params.social]]
	name = "Email"
	icon = "fa fa-envelope fa-2x"
	weight = 1
	url = "mailto:a_poganatz@outlook.com"

